AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  BucketName:
    Type: String

Resources:
  BucketResource:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      VersioningConfiguration:
        Status: Enabled

Outputs:
  BucketName:
    Description: Name of the bucket
    Value: !Ref BucketResource
