AWSTemplateFormatVersion: "2010-09-09"

Description: An example template with an IAM role for a takss Lambda state machine.

Parameters:
  Layers:
    Description: A space separated list of Layer ARNs including version
    Type: String
    Default: ""

  EncodedEnvironment:
    Description: An environment dictionary encoded as key|value, pairs. If key or value contains $ , or | they should be prepended with $ and base64 encoded
    Type: String
    Default: ""

  DynamoDbTableArn:
    Description: The ARN of the DynamoDB Table to store output in
    Type: String
    MinLength: "1"

  DynamoDbTableName:
    Description: The Name of the DynamoDB Table to store output in
    Type: String
    MinLength: "1"

Conditions:
  HasLayers: !Not [!Equals [!Ref Layers, ""]]

Resources:
  TasksLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole

  TasksLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Role: !GetAtt TasksLambdaExecutionRole.Arn
      Code: ../../../tasks-lambda.zip
      Runtime: python3.11
      Timeout: 900
      Handler: index.lambda_handler
      Architectures:
        - arm64
      Layers: !If
        - HasLayers
        - !Split [' ', !Ref Layers]
        - !Ref AWS::NoValue
      Environment:
        Variables:
          ENCODED_ENVIRONMENT: !Sub 'KVSTORE_DYNAMODB_TABLE_NAME|${DynamoDbTableName},SAFETY_MULTIPLE|1.4,SAFETY_DELAY_MS|0,DELAY_MS|0,${EncodedEnvironment}'

          # # How much time to make sure is still available (the DELAY_MS value gets added on top of this)
          # SAFETY_MULTIPLE: 1.4
          # SAFETY_DELAY_MS: 0
          # # How many ms to wait after each task
          # DELAY_MS: 0
  TasksLambdaDynamoPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Sub '${AWS::StackName}-TasksLambdaDynamoPolicy'
      Description: Managed policy for the tasks Lambda function launched by CloudFormation
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - dynamodb:Query
              - dynamodb:PutItem
              - dynamodb:GetItem
              - dynamodb:UpdateItem
              - dynamodb:DeleteItem
            Resource:
              - !Ref DynamoDbTableArn

      # Define the role here, rather than the managed policy on the role, to avoid a circular dependency
      Roles:
        - !Ref TasksLambdaExecutionRole

  TasksLambdaCloudWatchPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Sub '${AWS::StackName}-TasksLambdaCloudWatchPolicy'
      Description: Managed policy for the tasks Lambda function
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - logs:CreateLogStream
            Resource:
              - !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:${TasksLambdaLogGroup}:*"
          - Effect: Allow
            Action:
              - logs:PutLogEvents
            Resource:
              - !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:${TasksLambdaLogGroup}:*"

      # Define the role here, rather than the managed policy on the role, to avoid a circular dependency
      Roles:
        - !Ref TasksLambdaExecutionRole

  # See https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/147
  # https://typicalrunt.me/2019/09/20/enforcing-least-privilege-when-logging-lambda-functions-to-cloudwatch/
  # WARNING: If the lambda function gets updated, its name will change, so the log group will change, so the old logs will get deleted despite the retention period here.
  TasksLambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${TasksLambdaFunction}"
      RetentionInDays: 30

  StatesExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - !Sub states.${AWS::Region}.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: StatesExecutionPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource: '*'

  StateMachine:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      RoleArn: !GetAtt StatesExecutionRole.Arn
      Definition:
        Comment: Call a task-handling lambda function, retry on failure
        StartAt: LambdaWithRetries
        States:
          LambdaWithRetries:
            Type: Task
            Resource: !GetAtt TasksLambdaFunction.Arn
            Retry:
              - ErrorEquals: [Abort]
                MaxAttempts: 0
              - ErrorEquals: [States.ALL]
                IntervalSeconds: 20
                MaxAttempts: 4
                BackoffRate: 1.2
            End: true

Outputs:
  StateMachineArn:
    Description: The ARN of the state machine that keeps the tasks lambda running
    Value: !Ref StateMachine

  StateMachineName:
    Description: The Name of the state machine that keeps the tasks lambda running
    Value: !GetAtt StateMachine.Name
