AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  Domain:
    Description: Domain for API
    Type: String

  HostedZoneId:
    Description: Hosted Zone Id in which you want to add validation records
    Type: String

Resources:
  AcmCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref Domain
      DomainValidationOptions:
        - DomainName: !Ref Domain
          HostedZoneId: !Ref HostedZoneId
      ValidationMethod: DNS

Outputs:
  CertificateArn:
    Description: ACM Certificate ARN
    Value: !Ref AcmCertificate
